name: macos build checks

on: workflow_dispatch

jobs:
  build:
    runs-on: [macos-latest]
    steps:
    - run: uname -m
    - uses: actions/checkout@v3
    - run: python platforms/ios/build_framework.py ios
